disabled_rules: # rule identifiers to exclude from running
- line_length
- trailing_whitespace
- variable_name
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
opening_brace: error



